### ISSUE TITLE
Hackathon Deliverable 1

### ISSUE THREAD

**Issue by swoloszynski** [swoloszynski/imho#17]
### What
- https://rrhoover.typeform.com/to/OR0yRC
- This is due November 5th at 11:59PM PT. Only one teammate needs to fill this out this form.
- [x]  What's the link to your Upcoming Page?
- [x] Please explain your hackathon project in a tweet. 140 characters or less (not 280)! 
- [x] Do you have any questions for us? 
- [x] Which category are you competing for? Social Impact

### Dependencies
- Blocked by #15

**Comment by btrav** [comment]
Some suggestions:

What's the link to your Upcoming Page?

1. Product Name: IMHO
2. Tagline (up to 60 char): Get out of your echo chamber
3. [Topics](https://www.producthunt.com/topics): News, Education, Productivity?
4. Introduction (up to 300 char): Hi, we're Sam and Ben - both travelers who've worked with startups and educational organizations over the past few years. Now we're working to expand worldviews and facilitate discussions to reverse the increasing trend of political polarization through intelligent discussion.
5. Product Explanation: IMHO facilitates thought-provoking, fact-based, discussions from multiple points of view around timely topics with the aim of combatting echo chambers. Each topic will contain a primary write-up from each side with an option to respectfully respond to each other.
6. Call to Action: Expand your worldview with knowledge from the other side...
7. Success Notice: Thanks for making the world a better place! We'll be in touch shortly.
8. Logo: TBD #9
9. Background Image: https://unsplash.com/photos/Qp8mmuK27MI, https://unsplash.com/photos/u8rDR7cFrdM, https://unsplash.com/photos/gcDwzUGuUoI, https://unsplash.com/photos/ABGaVhJxwDQ


Please explain your hackathon project in a tweet. 140 characters or less (not 280)!
> IMHO facilitates thought-provoking discussions from multiple POVs around timely topics to combat echo chambers and #fakenews.

**Comment by btrav** [comment]
@swoloszynski I'll plan on submitting the "First Deliverable" this evening unless I hear otherwise from you.

**Comment by btrav** [comment]
First Deliverable Submitted!

Ship URL: https://www.producthunt.com/upcoming/imho-2
_Totally down to change this page later. Copy didn't come out as well as I'd hoped_ 😓

FYI - Ship Widget: https://gist.github.com/btrav/25cf9a300d84dc6d18b8ab4333d940ee

**Comment by swoloszynski** [comment]
Looks great, thanks for submitting!

**Comment by swoloszynski** [comment]
Feel free to close this issue since it's done :)
