### ISSUE TITLE
Grab domain name

### ISSUE THREAD

**Issue by btrav** [swoloszynski/imho#18]
Some domain suggestions (I usually use namecheap):

- goimho.com
- imhoimho.com
- imho.press
- imho.observer
- imho.club
- imho.community
- imho.watch

**Comment by swoloszynski** [comment]
- Do we have a max budget for this? 
- We could potentially defer this and use less pretty free domain names (ie imho.github.io) for now. Not opposed to getting a domain name, just wanted to note the option. 
- I'm happy to do this ticket. I like namecheap; I use Hover for the two domains I have right now

**Comment by btrav** [comment]
IDK, $5-$20? Then we could use github pages like you suggested. No strong feels for namecheap or hover, so whatever you're most comfortable with.

Happy to Venmo you half of what you spend, does that sound reasonable?

**Comment by swoloszynski** [comment]
Got imho.press for $2.06 🚀
