### ISSUE TITLE
Wire frames for article view

### ISSUE THREAD

**Issue by swoloszynski** [swoloszynski/imho#2]
### What
- Header / link back to home/categories
- Breadcrumbs to see what category you're on?
- Article content laid out side by side? Another lay out? 
- Desktop and mobile
- Research if other sites have similar layouts for inspiration
- Use sample content

**Comment by swoloszynski** [comment]
@btrav You can take the first stab at this one if you want and then we can iterate on it / try and figure out how to do mobile. Also if mobile is taking some time to figure out, we can separate them into two tickets.

**Comment by btrav** [comment]
Now I'm wondering if it would be better to have a topic and then break it down into manageable paragraphs for different subpoints instead of having two complete articles side-by-side.

**Comment by btrav** [comment]
Here's more of what I'm thinking:

![article v6](https://user-images.githubusercontent.com/5813935/32761757-5fa5a3de-c8b2-11e7-9d3a-602b0e91a6d2.png)

We could take articles that are already written and find the most comparable sections related to a specific topic (we could even use different articles or different authors, but we may want to try this approach first for the sake of simplicity). By comparing one paragraph at a time, in an accordion style on mobile, that could make the content more manageable to read.

**Comment by swoloszynski** [comment]
These look really cool. Have you shown them to Alison? I'd love to get them in front of people and see if others think this makes sense. (Could separate that into another ticket if we want)

**Comment by swoloszynski** [comment]
@btrav Can we have another discussion about this?

**Comment by swoloszynski** [comment]
Note - we'll add the iterations of these mockups to the build article page ticket #11
