### ISSUE TITLE
Week 2 deliverable

### ISSUE THREAD

**Issue by swoloszynski** [swoloszynski/imho#22]
### What
- Force Tom and Alison to sign up for email list
- Send email to ship subscribers
- Ask for feedback

**Comment by btrav** [comment]
Link for people to sign up: https://www.producthunt.com/upcoming/imho-2

**Comment by swoloszynski** [comment]
Link for survey to fill out: https://rrhoover.typeform.com/to/iSryDR

**Comment by btrav** [comment]
Oh man – for some reason I thought the deliverable was due at the end of today. Submitted a quick message. Late :( Sorry.

**Comment by swoloszynski** [comment]
Sorry I totally didn't keep track of this eitehr
