### ISSUE TITLE
Research frameworks

### ISSUE THREAD

**Issue by swoloszynski** [swoloszynski/imho#3]
### What
- Timebox
- [x] Note pros/cons of 3 or 4 different frameworks
- [x] Outcome: decide on a framework to use

**Comment by swoloszynski** [comment]
Candidates: Django, Node.js, Wordpress?, Jekyll / static site generator
Also research hosting options! (For prototype, aka scale is not a factor)

**Comment by swoloszynski** [comment]
### Factors: 
- How fast can we get it up and running? How easily can we deploy changes? 
- How much complexity is there for storing data? 
- Ease of styling the front end? 
- Current familiarity? 
- Interest in learning tech? 
- Free hosting options? 
- Match our needs? (Store and display blog posts, organize by categories, basic styling on the front end) 

### Highlevel
- MVC (model view controller) framework - better for sites with a lot of user interaction / custom rendered pages based on user / interactions, scales for large amounts of content well, more work to build.
- Static site generator - less work to build, not as good for scaling for many articles. I think this will meet our needs for an MVP very well, which is why I'm leaning Jekyll. 

### Options
- Django (MVC)
  - I've used this a lot before, so I'd have a head start on the learning curve. 
  - Django has a lot of out-of-the-box features, including a complete admin interface for editing content and user management. 
  - Displaying content requires us to build some routing and use the Django templating system to build the pages. 
  - Requires using a DB - integrates well with PostgreSQL. Built-in ORM (object relationship model) abstracts away a layer of db management, so we wouldn't have to do direct SQL. 
  - We could easily host this on Heroku's free tier, which I've done with some side projects in the past. 
- Node.js (You can build an MVC on top of this by picking other pieces of the stack)
  - I've worked with this a lot, and I think it's best used for more full-featured web apps. Otherwise, it allows so much flexibility that we'd have to build a lot from scratch, and I'd expect that to slow us down.
- Wordpress
  - Learning to customize Wordpress sites isn't something I'm particularly keen on. The development set up is kind of a pain and those skills aren't really applicable to much else I'd want to work on in the future. If you've used this before, liked it, and have a head start on the learning curve, I'd reconsider it
- Jekyll (Static site)
  - Static site, so this wouldn't require us to set up or host a database, manage schemas, etc. Definitely easier to set up hosting (and free!)
  - Has templating built in that's similar to Django's templating
  - Uses SASS for CSS, which I've used before and I'd recommend for more organized CSS with any framework we choose
- Ruby on Rails
  - A reasonable alternative to Django that I have less experience with. We can investigate further if we decide to go the MVC route.

### Other libraries
- I like this css library called [Materialize](http://materializecss.com/). It's similar to bootstrap, but has material design concepts.

**Comment by swoloszynski** [comment]
@btrav Feel free to take a look at these notes! I'm leaning Jekyll but open to discuss other options

**Comment by btrav** [comment]
@swoloszynski Also on-board w/ Jekyll. It'll likely be harder to switch at a later point if this thing really takes off, but I think it's worth using for this month to get things started ASAP.

I've never seen Materialize, but it looks dope. 🎉

**Comment by swoloszynski** [comment]
`It'll likely be harder to switch at a later point if this thing really takes off, but I think it's worth using for this month to get things started ASAP.` - I definitely agree, and I think we can cross that bridge when we get there. Jekyll won't scale well for adding tons of articles and it doesn't work for adding web-app-type features, but that if viewing traffic goes up a ton, we'll be able to scale for a while and buy ourselves some time before having to rebuild.
