### ISSUE TITLE
Week 3 Deliverable

### ISSUE THREAD

**Issue by swoloszynski** [swoloszynski/imho#31]
Todo: drop email notes / link here

**Comment by btrav** [comment]
![imho__surveys](https://user-images.githubusercontent.com/5813935/33002029-c56faa00-cd6e-11e7-9541-7c29139004f9.png)

Hah! Looking for an alternative.

**Comment by btrav** [comment]
So apparently we without the pro plan we can't use surveys or send more than one message a week to subscribers...smh. I just used Google Forms.
 
Survey link: https://goo.gl/forms/8VusGDR5CwxSH1Xv2

Also, confirming our only subscribers are ourselves, Alison, and Tom 😅 . I'm going to send to my parents this week. Maybe Taylor wants to give feedback, too? 🤷‍♂️

**Comment by btrav** [comment]
Also confirming that the Product Hunt deliverable has been sent.
