### ISSUE TITLE
Idea pitch copy

### ISSUE THREAD

**Issue by swoloszynski** [swoloszynski/imho#5]
### What
- One sentence tagline
- Three sentence description of project
- 30 second elevator pitch
- Add to project wiki

**Comment by swoloszynski** [comment]
Tagline and description are covered in #9. We can still use this ticket for the elevator pitch and close it once we've added it to the wiki.

**Comment by btrav** [comment]
Added an elevator pitch to the wiki: https://github.com/swoloszynski/imho/wiki/Brand
Let's make necessary tweaks then close.

**Comment by swoloszynski** [comment]
It looks great! 👍
