### ISSUE TITLE
Select topics for original content

### ISSUE THREAD

**Issue by swoloszynski** [swoloszynski/imho#7]
### What
- Pick topics we want to solicit new/original articles about

**Comment by btrav** [comment]
Lists with topics: 
* https://www.isidewith.com/polls
* https://www.ranker.com/list/political-issues-that-matter-the-most/mike-rothschild
* http://www.pewresearch.org/topics/
* http://www.democratichub.com/issues
* http://www.ontheissues.org/Issues.htm

Some suggestions that seem timely:
* Healthcare Reform
* Gun Policy
* Estate Tax
* Border Wall
* Campaign Finance Reform
* Fracking
* Charter Schools
* Military Drones
* Euthanasia

**Comment by swoloszynski** [comment]
I dropped these in the wiki

**Comment by swoloszynski** [comment]
https://github.com/swoloszynski/imho/wiki/Topics
