### ISSUE TITLE
Create Brand Identity for IMHO

### ISSUE THREAD

**Issue by btrav** [swoloszynski/imho#9]
- [x] Voice/tone
- [x] Mission
- [x] Vision
- [x] Logo
- [x] Tag line
- [x] Typefaces
- [x] Color scheme

**Comment by btrav** [comment]
* Voice/Tone
  * Voice
    * All communication from IMHO should be unbiased to gain the trust of readers and approachable to invite interested parties with varying levels of subject matter expertise. The structure and voice of IMHO should stay neutral and straightforward, to provide a fair and balanced platform for debates with a focus on facts.
We use the following brand guidelines to assure our message resonates consistently through all channels including our website, emails, social, print, investor documents, and annual reports.
  * Tone
    * Analytical, Transparent, Thoughtful, Civil, NOT Incendiary, Sensationalist, or Flippant
* Vision
  * Expanding worldviews through balanced discussions
* Mission
  * IMHO facilitates thought-provoking, fact-based, discussions from multiple points of view around timely topics with the aim of combatting echo chambers. Each topic will contain a primary write-up from each side with an option to respectfully respond to each other.
* Logo
  * A few different options here:
![logos1-01](https://user-images.githubusercontent.com/5813935/32417973-b9f9dcbe-c21e-11e7-8eea-1518e5a141c4.png)
* Tag Line/Essence
  * Get out of your echo chamber
* Typefaces
  * Logo - TBD
  * Header - For titles, we use [Vesper Libre](https://fonts.google.com/specimen/Vesper+Libre), a readable, comfortable serif font to invite readers. However, if that font is unavailable for titles, we use Georgia.
  * Body - For content, our primary font is [Open Sans](https://fonts.google.com/specimen/Open+Sans), which offers high readability and also parallels our focus on openness and transparency. However, if that font is unavailable for content, we use Arial.
* [Color Schemes](https://coolors.co/export/png/044b7f-3e885b-e2cd53-dd9d3e-131515) - Using black/white as often as possible -
  * Primary Color - Deep Sea Blue (hex #044B7F) for Trust
  * Secondary Color - New Shed Green (hex #3E885B) for Cooperation
  * Tertiary Colors - Ribbon Yellow (hex #E2CD53) for Optimism, Overripe Orange (hex #DD9D3E) for Confidence, and Darkwater Gray (hex #131515) for Stability

**Comment by btrav** [comment]
cc @swoloszynski, not sure if you saw the above yet.

**Comment by swoloszynski** [comment]
This looks great! 

- Copy is stellar
- I like the first two logos best. Do you have a favorite? 
- I really like the typefaces you chose.
- Color scheme - I really like all the thought you put into what the colors represent. I might be a careful with anything blue or red. Generally I like the concept, but I might want us to try tweaking a few of the hues. I do think that primarily b&w sounds good.

**Comment by swoloszynski** [comment]
Do you want to put these into a project wiki page so it's easy to find after we close the issue?

**Comment by btrav** [comment]
We chose the top left logo.

New colors:
#283593 indigo darken-3
#5c6bc0 indigo lighten-1

**Comment by btrav** [comment]
FYI - brand files are available in GDrive here: https://drive.google.com/drive/folders/1CEtGi4sMfG5l95edCkj8Bggd4xqcIg9y?usp=sharing
cc @swoloszynski

**Comment by swoloszynski** [comment]
We might want to commit them to the project to track changes and/or make them more accessible down the road in case we loose track of that Gdrive folder. Either way works for me.

**Comment by swoloszynski** [comment]
I dropped the link into the wiki for now
